apiVersion: frp.kubeinfra.io/v1alpha1
kind: FRPServer
metadata:
  name: frpserver-sample
  namespace: default
spec:
  version: "v1"
  
  # Basic server configuration
  bindAddr: "0.0.0.0"
  bindPort: 17000
  kcpBindPort: 17000
  proxyBindAddr: "0.0.0.0"

  allowPorts:
    - start: 2000
      end: 2000



  
  # Dashboard configuration
  webServer:
    port: 7500
    addr: "0.0.0.0"
    user: "admin"
    password: "admin"