//go:build !ignore_autogenerated

/*
Copyright 2024 The frp Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *APIMetadata) DeepCopyInto(out *APIMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new APIMetadata.
func (in *APIMetadata) DeepCopy() *APIMetadata {
	if in == nil {
		return nil
	}
	out := new(APIMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthOIDCServerConfig) DeepCopyInto(out *AuthOIDCServerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthOIDCServerConfig.
func (in *AuthOIDCServerConfig) DeepCopy() *AuthOIDCServerConfig {
	if in == nil {
		return nil
	}
	out := new(AuthOIDCServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthServerConfig) DeepCopyInto(out *AuthServerConfig) {
	*out = *in
	if in.AdditionalScopes != nil {
		in, out := &in.AdditionalScopes, &out.AdditionalScopes
		*out = make([]AuthScope, len(*in))
		copy(*out, *in)
	}
	out.OIDC = in.OIDC
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthServerConfig.
func (in *AuthServerConfig) DeepCopy() *AuthServerConfig {
	if in == nil {
		return nil
	}
	out := new(AuthServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectionStatus) DeepCopyInto(out *ConnectionStatus) {
	*out = *in
	in.ProxyConfig.DeepCopyInto(&out.ProxyConfig)
	in.StartTime.DeepCopyInto(&out.StartTime)
	in.LastCloseTime.DeepCopyInto(&out.LastCloseTime)
	if in.TrafficStats != nil {
		in, out := &in.TrafficStats, &out.TrafficStats
		*out = new(TrafficStats)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectionStatus.
func (in *ConnectionStatus) DeepCopy() *ConnectionStatus {
	if in == nil {
		return nil
	}
	out := new(ConnectionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRPServer) DeepCopyInto(out *FRPServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRPServer.
func (in *FRPServer) DeepCopy() *FRPServer {
	if in == nil {
		return nil
	}
	out := new(FRPServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FRPServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRPServerList) DeepCopyInto(out *FRPServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FRPServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRPServerList.
func (in *FRPServerList) DeepCopy() *FRPServerList {
	if in == nil {
		return nil
	}
	out := new(FRPServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FRPServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRPServerSpec) DeepCopyInto(out *FRPServerSpec) {
	*out = *in
	out.APIMetadata = in.APIMetadata
	in.Auth.DeepCopyInto(&out.Auth)
	out.SSHTunnelGateway = in.SSHTunnelGateway
	in.WebServer.DeepCopyInto(&out.WebServer)
	out.Log = in.Log
	in.Transport.DeepCopyInto(&out.Transport)
	if in.DetailedErrorsToClient != nil {
		in, out := &in.DetailedErrorsToClient, &out.DetailedErrorsToClient
		*out = new(bool)
		**out = **in
	}
	if in.AllowPorts != nil {
		in, out := &in.AllowPorts, &out.AllowPorts
		*out = make([]PortsRange, len(*in))
		copy(*out, *in)
	}
	if in.HTTPPlugins != nil {
		in, out := &in.HTTPPlugins, &out.HTTPPlugins
		*out = make([]HTTPPluginOptions, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRPServerSpec.
func (in *FRPServerSpec) DeepCopy() *FRPServerSpec {
	if in == nil {
		return nil
	}
	out := new(FRPServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FRPServerStatus) DeepCopyInto(out *FRPServerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.ServiceStatus.DeepCopyInto(&out.ServiceStatus)
	if in.ActiveConnections != nil {
		in, out := &in.ActiveConnections, &out.ActiveConnections
		*out = make([]*ConnectionStatus, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(ConnectionStatus)
				(*in).DeepCopyInto(*out)
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FRPServerStatus.
func (in *FRPServerStatus) DeepCopy() *FRPServerStatus {
	if in == nil {
		return nil
	}
	out := new(FRPServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPPluginOptions) DeepCopyInto(out *HTTPPluginOptions) {
	*out = *in
	if in.Ops != nil {
		in, out := &in.Ops, &out.Ops
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPPluginOptions.
func (in *HTTPPluginOptions) DeepCopy() *HTTPPluginOptions {
	if in == nil {
		return nil
	}
	out := new(HTTPPluginOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfig) DeepCopyInto(out *LoadBalancerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfig.
func (in *LoadBalancerConfig) DeepCopy() *LoadBalancerConfig {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LogConfig) DeepCopyInto(out *LogConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LogConfig.
func (in *LogConfig) DeepCopy() *LogConfig {
	if in == nil {
		return nil
	}
	out := new(LogConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortsRange) DeepCopyInto(out *PortsRange) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortsRange.
func (in *PortsRange) DeepCopy() *PortsRange {
	if in == nil {
		return nil
	}
	out := new(PortsRange)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyConfig) DeepCopyInto(out *ProxyConfig) {
	*out = *in
	if in.Transport != nil {
		in, out := &in.Transport, &out.Transport
		*out = new(TransportConfig)
		**out = **in
	}
	if in.LoadBalancer != nil {
		in, out := &in.LoadBalancer, &out.LoadBalancer
		*out = new(LoadBalancerConfig)
		**out = **in
	}
	if in.HealthCheck != nil {
		in, out := &in.HealthCheck, &out.HealthCheck
		*out = new(HealthCheckConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyConfig.
func (in *ProxyConfig) DeepCopy() *ProxyConfig {
	if in == nil {
		return nil
	}
	out := new(ProxyConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxyTypeCount) DeepCopyInto(out *ProxyTypeCount) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxyTypeCount.
func (in *ProxyTypeCount) DeepCopy() *ProxyTypeCount {
	if in == nil {
		return nil
	}
	out := new(ProxyTypeCount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QUICOptions) DeepCopyInto(out *QUICOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QUICOptions.
func (in *QUICOptions) DeepCopy() *QUICOptions {
	if in == nil {
		return nil
	}
	out := new(QUICOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHTunnelGateway) DeepCopyInto(out *SSHTunnelGateway) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHTunnelGateway.
func (in *SSHTunnelGateway) DeepCopy() *SSHTunnelGateway {
	if in == nil {
		return nil
	}
	out := new(SSHTunnelGateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServerTransportConfig) DeepCopyInto(out *ServerTransportConfig) {
	*out = *in
	if in.TCPMux != nil {
		in, out := &in.TCPMux, &out.TCPMux
		*out = new(bool)
		**out = **in
	}
	out.QUIC = in.QUIC
	out.TLS = in.TLS
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServerTransportConfig.
func (in *ServerTransportConfig) DeepCopy() *ServerTransportConfig {
	if in == nil {
		return nil
	}
	out := new(ServerTransportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceStatus) DeepCopyInto(out *ServiceStatus) {
	*out = *in
	out.Uptime = in.Uptime
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceStatus.
func (in *ServiceStatus) DeepCopy() *ServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSConfig) DeepCopyInto(out *TLSConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSConfig.
func (in *TLSConfig) DeepCopy() *TLSConfig {
	if in == nil {
		return nil
	}
	out := new(TLSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TLSServerConfig) DeepCopyInto(out *TLSServerConfig) {
	*out = *in
	out.TLSConfig = in.TLSConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TLSServerConfig.
func (in *TLSServerConfig) DeepCopy() *TLSServerConfig {
	if in == nil {
		return nil
	}
	out := new(TLSServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficStats) DeepCopyInto(out *TrafficStats) {
	*out = *in
	if in.TrafficIn != nil {
		in, out := &in.TrafficIn, &out.TrafficIn
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
	if in.TrafficOut != nil {
		in, out := &in.TrafficOut, &out.TrafficOut
		*out = make([]int64, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficStats.
func (in *TrafficStats) DeepCopy() *TrafficStats {
	if in == nil {
		return nil
	}
	out := new(TrafficStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransportConfig) DeepCopyInto(out *TransportConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransportConfig.
func (in *TransportConfig) DeepCopy() *TransportConfig {
	if in == nil {
		return nil
	}
	out := new(TransportConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebServerConfig) DeepCopyInto(out *WebServerConfig) {
	*out = *in
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(TLSConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebServerConfig.
func (in *WebServerConfig) DeepCopy() *WebServerConfig {
	if in == nil {
		return nil
	}
	out := new(WebServerConfig)
	in.DeepCopyInto(out)
	return out
}
